public class JsonResource {
	public class PrTipologia {
		public String codice {get; set;}
		public String valore {get; set;}
	}

	public class PrRating {
		public String codice {get; set;}
		public String valore {get; set;}
	}

	public class PrTipoLinea {
		public String codice {get; set;}
		public String valore {get; set;}
	}

	public class PrProposte {
		public String codice {get; set;}
		public String valore {get; set;}
	}
}